name: deepGesture
channels:
- menpo
- !!python/unicode
  'defaults'
dependencies:
- python=3.5
- pip==9.0.1
- numpy==1.12.0
- matplotlib==2.0.0
- scikit-learn==0.18.1
- scipy==0.19.0
- pandas==0.19.2
- pillow==4.0.0
- seaborn==0.7.1
- h5py==2.7.0
- opencv3=3.1.0
- pywget=2.2
- scikit-image==0.13.0
- pip:
  - tensorflow==1.1.0
  - theano==0.9.0
  - keras==2.0.4

